nsr:
  wsdl: "https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx"
  service: "ldb"
  port: "LDBServiceSoap"
  address: "https://lite.realtime.nationalrail.co.uk/OpenLDBWS/ldb11.asmx"

token:
  apikey: "![JB46+DlQnb+BLbbDq6Vohv/dF03xem58cycOb4eTAyThWlSBM10uvQ==]"
  
http:
  port: "8083"

serviceNow:
  port: "8087"
  host: "0.0.0.0"
  protocol: "HTTP"
  clientId: "452e961bff2c4e899f09a3afb5ffa099"
  clientSecret: "5447C65c460F4a9583f632B26C3c6c7a"